name: analytics
description: |-
  Submitting anonymized usage information.

  This usage helps us identify any problems with the integrations.

  The sent data only contains information about steps (id, version, runtime, error), NO logs or other data is included.
executable:
  osx: https://github.com/mateherber/bitrise-plugins-analytics/releases/download/fakeversion/bitrise-plugins-analytics-Darwin-x86_64
  linux: https://github.com/mateherber/bitrise-plugins-analytics/releases/download/fakeversion/bitrise-plugins-analytics-Linux-x86_64
trigger: DidFinishRun
requirements:
- tool: bitrise
  min_version: 1.41.0
  max_version: ""
